{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# Startup Idea Diversity Analysis\n",
        "\n",
        "This notebook compares startup idea diversity between **VS prompting** and **direct prompting**.\n",
        "\n",
        "## Experimental framing\n",
        "- **Input artifacts**: model generations and parsed ideas\n",
        "- **Measures**: semantic diversity, lexical diversity, and concept diversity\n",
        "- **Output**: visual comparison to inspect breadth and novelty of generated ideas"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## 1) Setup and Imports\n",
        "\n",
        "Load libraries and define helper utilities used throughout the notebook."
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "import json\n",
        "import re\n",
        "from pathlib import Path\n",
        "\n",
        "import numpy as np\n",
        "import pandas as pd\n",
        "import matplotlib.pyplot as plt\n",
        "import plotly.express as px\n",
        "import plotly.graph_objects as go\n",
        "from sentence_transformers import SentenceTransformer\n",
        "from sklearn.decomposition import PCA\n",
        "\n",
        "plt.style.use(\"seaborn-v0_8-whitegrid\")\n",
        "\n",
        "RESPONSE_BLOCK_RE = re.compile(r\"<response>(.*?)</response>\", re.DOTALL | re.IGNORECASE)\n",
        "TEXT_RE = re.compile(r\"<text>(.*?)</text>\", re.DOTALL | re.IGNORECASE)\n",
        "PROB_RE = re.compile(r\"<probability>\\s*([0-9]*\\.?[0-9]+)\\s*</probability>\", re.IGNORECASE)\n",
        "IDEA_LINE_RE = re.compile(r\"startup idea\\s*:\\s*(.+)\", re.IGNORECASE)\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## 2) Load Metrics and Parsed Ideas\n",
        "\n",
        "We load:\n",
        "- `data/diversity_metrics.json`\n",
        "- `data/parsed_vs_ideas.json`\n",
        "- `data/direct_outputs.json`\n",
        "\n",
        "For direct outputs, we parse `<response>` blocks and recover both idea text and probability."
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "metrics_path = Path(\"data/diversity_metrics.json\")\n",
        "vs_path = Path(\"data/parsed_vs_ideas.json\")\n",
        "direct_path = Path(\"data/direct_outputs.json\")\n",
        "\n",
        "metrics = json.loads(metrics_path.read_text(encoding=\"utf-8\"))\n",
        "vs_items = json.loads(vs_path.read_text(encoding=\"utf-8\"))\n",
        "direct_items = json.loads(direct_path.read_text(encoding=\"utf-8\"))\n",
        "\n",
        "def extract_idea(text: str) -> str:\n",
        "    text = text.strip()\n",
        "    for line in text.splitlines():\n",
        "        m = IDEA_LINE_RE.search(line.strip())\n",
        "        if m:\n",
        "            return m.group(1).strip()\n",
        "    return text\n",
        "\n",
        "def parse_direct_records(items):\n",
        "    records = []\n",
        "    for item in items:\n",
        "        topic = item.get(\"topic\", \"\")\n",
        "        raw = str(item.get(\"raw_output\", \"\"))\n",
        "        blocks = RESPONSE_BLOCK_RE.findall(raw)\n",
        "        for block in blocks:\n",
        "            text_match = TEXT_RE.search(block)\n",
        "            prob_match = PROB_RE.search(block)\n",
        "            if not text_match:\n",
        "                continue\n",
        "            idea = extract_idea(text_match.group(1))\n",
        "            prob = None\n",
        "            if prob_match:\n",
        "                try:\n",
        "                    prob = float(prob_match.group(1))\n",
        "                except ValueError:\n",
        "                    prob = None\n",
        "            records.append({\"topic\": topic, \"idea\": idea, \"probability\": prob})\n",
        "    return records\n",
        "\n",
        "vs_df = pd.DataFrame(vs_items)\n",
        "vs_df = vs_df[[\"topic\", \"idea\", \"probability\"]].copy()\n",
        "vs_df[\"method\"] = \"VS prompting\"\n",
        "\n",
        "direct_df = pd.DataFrame(parse_direct_records(direct_items))\n",
        "direct_df[\"method\"] = \"Direct prompting\"\n",
        "\n",
        "display(vs_df.head(3))\n",
        "display(direct_df.head(3))\n",
        "print(f\"VS ideas: {len(vs_df)}\")\n",
        "print(f\"Direct ideas parsed: {len(direct_df)}\")\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## 3) Bar Chart: Diversity Metric Comparison\n",
        "\n",
        "This chart compares the aggregate diversity measures reported by the metrics pipeline.\n",
        "\n",
        "- Semantic diversity\n",
        "- Distinct-1\n",
        "- Distinct-2\n",
        "- Concept diversity ratio"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "comparison_df = pd.DataFrame([\n",
        "    {\n",
        "        \"method\": \"VS prompting\",\n",
        "        \"semantic_diversity\": metrics[\"vs_prompting\"][\"semantic_diversity\"],\n",
        "        \"distinct_1\": metrics[\"vs_prompting\"][\"lexical_diversity\"][\"distinct_1\"],\n",
        "        \"distinct_2\": metrics[\"vs_prompting\"][\"lexical_diversity\"][\"distinct_2\"],\n",
        "        \"concept_diversity_ratio\": metrics[\"vs_prompting\"][\"concept_diversity\"][\"concept_diversity_ratio\"],\n",
        "    },\n",
        "    {\n",
        "        \"method\": \"Direct prompting\",\n",
        "        \"semantic_diversity\": metrics[\"direct_prompting\"][\"semantic_diversity\"],\n",
        "        \"distinct_1\": metrics[\"direct_prompting\"][\"lexical_diversity\"][\"distinct_1\"],\n",
        "        \"distinct_2\": metrics[\"direct_prompting\"][\"lexical_diversity\"][\"distinct_2\"],\n",
        "        \"concept_diversity_ratio\": metrics[\"direct_prompting\"][\"concept_diversity\"][\"concept_diversity_ratio\"],\n",
        "    },\n",
        "])\n",
        "\n",
        "melted = comparison_df.melt(id_vars=\"method\", var_name=\"metric\", value_name=\"value\")\n",
        "\n",
        "plt.figure(figsize=(10, 5))\n",
        "for i, method in enumerate(comparison_df[\"method\"]):\n",
        "    subset = melted[melted[\"method\"] == method]\n",
        "    x = np.arange(len(subset[\"metric\"])) + (i * 0.35)\n",
        "    plt.bar(x, subset[\"value\"], width=0.35, label=method)\n",
        "plt.xticks(np.arange(len(subset[\"metric\"])) + 0.175, subset[\"metric\"], rotation=20)\n",
        "plt.ylabel(\"Score\")\n",
        "plt.title(\"Diversity Metrics Comparison (Matplotlib)\")\n",
        "plt.legend()\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "fig = px.bar(\n",
        "    melted,\n",
        "    x=\"metric\",\n",
        "    y=\"value\",\n",
        "    color=\"method\",\n",
        "    barmode=\"group\",\n",
        "    title=\"Diversity Metrics Comparison (Plotly)\",\n",
        ")\n",
        "fig.show()\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## 4) Histogram: Idea Probability Distribution\n",
        "\n",
        "We compare probability values attached to generated ideas. Lower values indicate tail-sampled ideas under the prompt design."
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "vs_probs = pd.to_numeric(vs_df[\"probability\"], errors=\"coerce\").dropna()\n",
        "direct_probs = pd.to_numeric(direct_df[\"probability\"], errors=\"coerce\").dropna()\n",
        "\n",
        "plt.figure(figsize=(9, 5))\n",
        "bins = np.linspace(0, 0.1, 16)\n",
        "plt.hist(vs_probs, bins=bins, alpha=0.6, label=\"VS prompting\")\n",
        "plt.hist(direct_probs, bins=bins, alpha=0.6, label=\"Direct prompting\")\n",
        "plt.xlabel(\"Probability\")\n",
        "plt.ylabel(\"Count\")\n",
        "plt.title(\"Histogram of Idea Probabilities (Matplotlib)\")\n",
        "plt.legend()\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "prob_df = pd.concat([\n",
        "    pd.DataFrame({\"method\": \"VS prompting\", \"probability\": vs_probs}),\n",
        "    pd.DataFrame({\"method\": \"Direct prompting\", \"probability\": direct_probs}),\n",
        "], ignore_index=True)\n",
        "\n",
        "fig = px.histogram(\n",
        "    prob_df,\n",
        "    x=\"probability\",\n",
        "    color=\"method\",\n",
        "    nbins=15,\n",
        "    barmode=\"overlay\",\n",
        "    opacity=0.7,\n",
        "    title=\"Histogram of Idea Probabilities (Plotly)\",\n",
        ")\n",
        "fig.show()\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## 5) PCA Scatter Plot of Idea Embeddings\n",
        "\n",
        "We project sentence embeddings into 2D with PCA to visually inspect how broadly each prompting method explores idea space."
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "combined_df = pd.concat([\n",
        "    vs_df[[\"topic\", \"idea\", \"method\"]],\n",
        "    direct_df[[\"topic\", \"idea\", \"method\"]],\n",
        "], ignore_index=True).dropna(subset=[\"idea\"])\n",
        "\n",
        "encoder = SentenceTransformer(\"all-MiniLM-L6-v2\")\n",
        "embeddings = encoder.encode(combined_df[\"idea\"].tolist(), normalize_embeddings=True, show_progress_bar=True)\n",
        "\n",
        "pca = PCA(n_components=2, random_state=42)\n",
        "coords = pca.fit_transform(embeddings)\n",
        "combined_df[\"pc1\"] = coords[:, 0]\n",
        "combined_df[\"pc2\"] = coords[:, 1]\n",
        "\n",
        "plt.figure(figsize=(8, 6))\n",
        "for method in combined_df[\"method\"].unique():\n",
        "    subset = combined_df[combined_df[\"method\"] == method]\n",
        "    plt.scatter(subset[\"pc1\"], subset[\"pc2\"], alpha=0.7, label=method)\n",
        "plt.title(\"PCA Projection of Idea Embeddings (Matplotlib)\")\n",
        "plt.xlabel(\"PC1\")\n",
        "plt.ylabel(\"PC2\")\n",
        "plt.legend()\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "fig = px.scatter(\n",
        "    combined_df,\n",
        "    x=\"pc1\",\n",
        "    y=\"pc2\",\n",
        "    color=\"method\",\n",
        "    hover_data=[\"topic\", \"idea\"],\n",
        "    title=\"PCA Projection of Idea Embeddings (Plotly)\",\n",
        ")\n",
        "fig.show()\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## 6) Cluster Distribution Comparison\n",
        "\n",
        "Finally, we visualize how ideas distribute across discovered concept clusters for each method."
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "def cluster_df_from_metrics(section_name: str, payload: dict) -> pd.DataFrame:\n",
        "    cluster_map = payload[section_name][\"concept_diversity\"][\"cluster_distribution\"]\n",
        "    df = pd.DataFrame({\n",
        "        \"cluster\": list(cluster_map.keys()),\n",
        "        \"count\": list(cluster_map.values()),\n",
        "    })\n",
        "    df[\"method\"] = \"VS prompting\" if section_name == \"vs_prompting\" else \"Direct prompting\"\n",
        "    return df\n",
        "\n",
        "cluster_vs = cluster_df_from_metrics(\"vs_prompting\", metrics)\n",
        "cluster_direct = cluster_df_from_metrics(\"direct_prompting\", metrics)\n",
        "cluster_df = pd.concat([cluster_vs, cluster_direct], ignore_index=True)\n",
        "\n",
        "plt.figure(figsize=(10, 5))\n",
        "for method in cluster_df[\"method\"].unique():\n",
        "    subset = cluster_df[cluster_df[\"method\"] == method].sort_values(\"cluster\")\n",
        "    plt.bar(subset[\"cluster\"] + \" (\" + method + \")\", subset[\"count\"], alpha=0.8, label=method)\n",
        "plt.xticks(rotation=45, ha=\"right\")\n",
        "plt.ylabel(\"Ideas per cluster\")\n",
        "plt.title(\"Cluster Distribution by Prompting Method (Matplotlib)\")\n",
        "plt.tight_layout()\n",
        "plt.show()\n",
        "\n",
        "fig = px.bar(\n",
        "    cluster_df,\n",
        "    x=\"cluster\",\n",
        "    y=\"count\",\n",
        "    color=\"method\",\n",
        "    barmode=\"group\",\n",
        "    title=\"Cluster Distribution by Prompting Method (Plotly)\",\n",
        ")\n",
        "fig.show()\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "## 7) Interpretation Notes\n",
        "\n",
        "Use this section to summarize findings after running all cells:\n",
        "\n",
        "- Which method has higher semantic diversity?\n",
        "- Are lexical diversity gains aligned with semantic gains?\n",
        "- Does one method populate clusters more evenly?\n",
        "- Are probability distributions concentrated near the low-probability tail?"
      ]
    }
  ],
  "metadata": {
    "kernelspec": {
      "display_name": "Python 3",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "name": "python",
      "version": "3"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 5
}
